wip

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,8 @@
+#!/bin/sh
 yarn lint;
+# Check for modified/untracked files
+if ! git diff --quiet; then
+  echo "Error: There are uncommitted changes in the working directory."
+  echo "Please commit or stash them before running this script."
+  exit 1
+fi
